# Site settings
title: Yet another blog about programming
description: > # this means to ignore newlines until "baseurl:"
  Yet another blog about programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dkandalov.github.io" # the base hostname & protocol for your site
twitter_username: dmitrykandalov
github_username:  dkandalov
email:

# Build settings
markdown: kramdown