# Site settings
title: Enterprise xml best programming practices patterns
description: > # this means to ignore newlines until "baseurl:"
  Dmitry Kandalov blog about programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dkandalov.github.io" # the base hostname & protocol for your site
twitter_username: dmitrykandalov
github_username:  dkandalov
email:

# Build settings
markdown: kramdown
sass:
    style: :compressed

# Gems
plugins: [jekyll-paginate]